---
- name: Create domain configs
  template:
    src: config
    dest: "{{ letsencrypt_config_dir}}/{{ item.name }}.ini"
  with_items: "{{ letsencrypt_domains_list|default(omit) }}"
  when: letsencrypt_domains_list is defined

- name: Create secrets
  template:
    src: secret
    mode: 0600
    owner: root
    group: root
    dest: "{{ letsencrypt_dns_secrets_dir}}/{{ item.name }}.ini"
  with_items: "{{ letsencrypt_dns_secrets }}"
  when: letsencrypt_dns_secrets is defined

- name: Create LE dir
  file:
    path: "/etc/letsencrypt"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Get certificates
  command: "{{ letsencrypt_executable }} certonly -n -c {{ letsencrypt_config_dir }}/{{ item.name }}.ini"
  with_items: "{{ letsencrypt_domains_list|default(omit) }}"
  when: letsencrypt_domains_list is defined
