---
- name: Remove in apt if exists - Ubuntu
  apt:
    name: certbot
    state: absent

- name: Install snap if not present
  apt:
    name: snapd
    state: present

- name: Install Certbot Snap - Ubuntu
  snap:
    name: certbot
    state: present
    classic: yes
