---
- name: Create docker dir
  file:
    path: "{{ letsencrypt_docker_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  when: "letsencrypt_install_method == 'docker'"

- name: Create docker compose file
  template:
    src: docker-compose
    mode: 0644
    owner: root
    group: root
    dest: "{{ letsencrypt_docker_compose_yml }}"
  when: "letsencrypt_install_method == 'docker'"
