---
- name: Remove in apt if exists - Ubuntu
  apt:
    name: certbot
    state: absent

- name: Install snap if not present
  apt:
    name: snapd
    state: present

- name: Remove Certbot - Ubuntu
  snap:
    name: certbot
    state: absent

- name: Install plugins
  pip:
    name: "{{ letsencrypt_pip_packages }}"
    state: latest
    executable: pip3
